(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"DMsimpt-quarks",
  Authors -> {"Andre Lessa"},
  Version -> "1.1",
  Date -> "22.06.2026"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], Xs -> S[4], YFu -> F[13], YFd -> F[14]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MX,
    Indices -> {},
    PropagatorLabel -> "Xs" },

F[13] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MYu,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "YFu" },

F[14] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MYd,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "YFd" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ S[4] ] = GaugeXi[S[100]];
GaugeXi[ F[13] ] = GaugeXi[F[200]];
GaugeXi[ F[14] ] = GaugeXi[F[300]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MTA[ ___ ] := MTA;
MT[ ___ ] := MT;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
MX[ ___ ] := MX;
MYu[ ___ ] := MYu;
MYd[ ___ ] := MYd;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ F[13, {__}] ] := TheLabel[F[13]];
TheLabel[ F[14, {__}] ] := TheLabel[F[14]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-2*I)*lamXsH, 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-2*I)*lamXsH, 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-2*I)*lamXsH, 0}},

C[ S[1] , S[4] , S[4] ] == {{(-2*I)*lamXsH*vev, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*lamXs, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{I*EL, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc18, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc19, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc21, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc24, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc25, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc27, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc29, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc32, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc33, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(EL^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc35, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc37, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(EL^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc39, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[14, {e1x2}] , F[14, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{YFd, YFd}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{YFd, YFd}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MYd}, {}] + MYd*FR$deltaZ[{YFd, YFd}, {{}}, "L"] + MYd*FR$deltaZ[{YFd, YFd}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MYd}, {}] + MYd*FR$deltaZ[{YFd, YFd}, {{}}, "L"] + MYd*FR$deltaZ[{YFd, YFd}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{YFu, YFu}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{YFu, YFu}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MYu}, {}] + MYu*FR$deltaZ[{YFu, YFu}, {{}}, "L"] + MYu*FR$deltaZ[{YFu, YFu}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MYu}, {}] + MYu*FR$deltaZ[{YFu, YFu}, {{}}, "L"] + MYu*FR$deltaZ[{YFu, YFu}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc43*SUNF[e3x2, e1x1, e2x1], -1/2*(GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/aS}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc45*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {(-I)*gc45*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc45*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc46L*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MB)}, {gc46R*IndexDelta[e1x2, e2x2], -1/2*(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MT}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc47L*IndexDelta[e1x2, e2x2], -1/2*(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {gc47R*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MB)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc48*IndexDelta[e1x2, e2x2], ((-1/2*I)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc48*IndexDelta[e1x2, e2x2], ((-1/2*I)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[6] , F[3] , -S[3] ] == {{gc50, 0}, {0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc51L, 0}, {gc51R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc52, 0}, {I*gc52, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc53L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MT)}, {gc53R*IndexDelta[e1x2, e2x2], -1/2*(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MB}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc54L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MT)}, {gc54R*IndexDelta[e1x2, e2x2], -1/2*(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc55*IndexDelta[e1x2, e2x2], ((-1/2*I)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc55*IndexDelta[e1x2, e2x2], ((-1/2*I)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[14, {e2x2}] , S[4] ] == {{I*gc57*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{d, d}, {{}}, "R"] + FR$deltaZ[{YFd, YFd}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -F[11, {e1x2}] , F[14, {e2x2}] , S[4] ] == {{I*gc58*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{s, s}, {{}}, "R"] + FR$deltaZ[{YFd, YFd}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -F[12, {e1x2}] , F[14, {e2x2}] , S[4] ] == {{I*gc59*IndexDelta[e1x2, e2x2], (-1/2*I)*yFbR*(FR$deltaZ[{b, b}, {{}}, "R"] + FR$deltaZ[{YFd, YFd}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -F[7, {e1x2}] , F[13, {e2x2}] , S[4] ] == {{I*gc60*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{u, u}, {{}}, "R"] + FR$deltaZ[{YFu, YFu}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -F[8, {e1x2}] , F[13, {e2x2}] , S[4] ] == {{I*gc61*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{c, c}, {{}}, "R"] + FR$deltaZ[{YFu, YFu}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -F[9, {e1x2}] , F[13, {e2x2}] , S[4] ] == {{I*gc62*IndexDelta[e1x2, e2x2], (-1/2*I)*yFtR*(FR$deltaZ[{t, t}, {{}}, "R"] + FR$deltaZ[{YFu, YFu}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -F[14, {e1x2}] , F[10, {e2x2}] , S[4] ] == {{0, 0}, {I*gc63R*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{d, d}, {{}}, "R"] + FR$deltaZ[{YFd, YFd}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}},

C[ -F[14, {e1x2}] , F[11, {e2x2}] , S[4] ] == {{0, 0}, {I*gc64R*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{s, s}, {{}}, "R"] + FR$deltaZ[{YFd, YFd}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}},

C[ -F[14, {e1x2}] , F[12, {e2x2}] , S[4] ] == {{0, 0}, {I*gc65R*IndexDelta[e1x2, e2x2], (-1/2*I)*yFbR*(FR$deltaZ[{b, b}, {{}}, "R"] + FR$deltaZ[{YFd, YFd}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}},

C[ -F[13, {e1x2}] , F[7, {e2x2}] , S[4] ] == {{0, 0}, {I*gc66R*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{u, u}, {{}}, "R"] + FR$deltaZ[{YFu, YFu}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}},

C[ -F[13, {e1x2}] , F[8, {e2x2}] , S[4] ] == {{0, 0}, {I*gc67R*IndexDelta[e1x2, e2x2], (-1/2*I)*yFqR*(FR$deltaZ[{c, c}, {{}}, "R"] + FR$deltaZ[{YFu, YFu}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}},

C[ -F[13, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{0, 0}, {I*gc68R*IndexDelta[e1x2, e2x2], (-1/2*I)*yFtR*(FR$deltaZ[{t, t}, {{}}, "R"] + FR$deltaZ[{YFu, YFu}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*EL^2/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ S[2] , -S[3] , V[3] ] == {{((-1/2*I)*EL)/sw, 0}},

C[ -S[3] , S[1] , V[3] ] == {{EL/(2*sw), 0}},

C[ V[1] , V[3] , -V[3] ] == {{I*EL, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{((I/2)*EL)/sw, 0}},

C[ S[3] , S[1] , -V[3] ] == {{EL/(2*sw), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-2*I)*gc84, 0}, {I*gc84, 0}, {I*gc84, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-2*I)*gc86, 0}, {I*gc86, 0}, {I*gc86, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc87R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{(EL*(cw^2 + sw^2))/(2*cw*sw), 0}},

C[ S[3] , -S[3] , V[2] ] == {{((I/2)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*EL^2/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-1/2*(EL^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc97, 0}, {(-I)*gc97, 0}, {(2*I)*gc97, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-2*I)*gc102, 0}, {I*gc102, 0}, {I*gc102, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc103, 0}, {I*gc103, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc104, 0}, {I*gc104, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc105, 0}, {I*gc105, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc106*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc106*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc107*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc107*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc108*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc108*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc109*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc109*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc110*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc110*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc111*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc111*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc116*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc116*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc117*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc117*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc118*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc118*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc119*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc119*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc120*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc120*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc121*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc121*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc122*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc123*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc124*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc125*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc126*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc127*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc128, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc129, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc130, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc131, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc132, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc133, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc134L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc134R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc135L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc135R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc136L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc136R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc137L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc137R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc138L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc138R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc139L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc139R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc140, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc141, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc142, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc143L, 0}, {I*gc143R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc144L, 0}, {I*gc144R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc145L, 0}, {I*gc145R, 0}},

C[ -F[14, {e1x2}] , F[14, {e2x2}] , V[1] ] == {{I*gc146*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{YFd, YFd}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc146*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{YFd, YFd}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] , V[1] ] == {{I*gc147*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{YFu, YFu}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc147*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{YFu, YFu}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] , V[4, {e3x2}] ] == {{I*gc148*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{YFu, YFu}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc148*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{YFu, YFu}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[14, {e1x2}] , F[14, {e2x2}] , V[4, {e3x2}] ] == {{I*gc149*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{YFd, YFd}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc149*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{YFd, YFd}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[14, {e1x2}] , F[14, {e2x2}] , V[2] ] == {{I*gc150*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{YFd, YFd}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/cw}, {I*gc150*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{YFd, YFd}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] , V[2] ] == {{I*gc151*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{YFu, YFu}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/cw}, {I*gc151*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{YFu, YFu}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc18 -> -EL,
     gc19 -> EL,
     gc21 -> -EL,
     gc24 -> EL,
     gc25 -> (cw*EL)/sw,
     gc27 -> -((cw*EL)/sw),
     gc29 -> EL,
     gc32 -> -EL,
     gc33 -> -((cw*EL)/sw),
     gc35 -> (cw*EL)/sw,
     gc37 -> -((cw*EL)/sw),
     gc39 -> (cw*EL)/sw,
     gc43 -> -GS,
     gc45 -> GS^2,
     gc46L -> yb,
     gc46R -> -yt,
     gc47L -> -(yb/Sqrt[2]),
     gc47R -> yb/Sqrt[2],
     gc48 -> -(yb/Sqrt[2]),
     gc50 -> ytau,
     gc51L -> -(ytau/Sqrt[2]),
     gc51R -> ytau/Sqrt[2],
     gc52 -> -(ytau/Sqrt[2]),
     gc53L -> yt,
     gc53R -> -yb,
     gc54L -> yt/Sqrt[2],
     gc54R -> -(yt/Sqrt[2]),
     gc55 -> -(yt/Sqrt[2]),
     gc57 -> -yFqR,
     gc58 -> -yFqR,
     gc59 -> -yFbR,
     gc60 -> -yFqR,
     gc61 -> -yFqR,
     gc62 -> -yFtR,
     gc63R -> -yFqR,
     gc64R -> -yFqR,
     gc65R -> -yFbR,
     gc66R -> -yFqR,
     gc67R -> -yFqR,
     gc68R -> -yFtR,
     gc84 -> EL^2,
     gc86 -> -(EL^2/sw^2),
     gc87R -> -ytau,
     gc97 -> -((cw*EL^2)/sw),
     gc102 -> (cw^2*EL^2)/sw^2,
     gc103 -> -EL,
     gc104 -> -EL,
     gc105 -> -EL,
     gc106 -> (2*EL)/3,
     gc107 -> (2*EL)/3,
     gc108 -> (2*EL)/3,
     gc109 -> -1/3*EL,
     gc110 -> -1/3*EL,
     gc111 -> -1/3*EL,
     gc116 -> GS,
     gc117 -> GS,
     gc118 -> GS,
     gc119 -> GS,
     gc120 -> GS,
     gc121 -> GS,
     gc122 -> EL/(Sqrt[2]*sw),
     gc123 -> EL/(Sqrt[2]*sw),
     gc124 -> EL/(Sqrt[2]*sw),
     gc125 -> EL/(Sqrt[2]*sw),
     gc126 -> EL/(Sqrt[2]*sw),
     gc127 -> EL/(Sqrt[2]*sw),
     gc128 -> EL/(Sqrt[2]*sw),
     gc129 -> EL/(Sqrt[2]*sw),
     gc130 -> EL/(Sqrt[2]*sw),
     gc131 -> EL/(Sqrt[2]*sw),
     gc132 -> EL/(Sqrt[2]*sw),
     gc133 -> EL/(Sqrt[2]*sw),
     gc134L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc134R -> (-2*EL*sw)/(3*cw),
     gc135L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc135R -> (-2*EL*sw)/(3*cw),
     gc136L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc136R -> (-2*EL*sw)/(3*cw),
     gc137L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc137R -> (EL*sw)/(3*cw),
     gc138L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc138R -> (EL*sw)/(3*cw),
     gc139L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc139R -> (EL*sw)/(3*cw),
     gc140 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc141 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc142 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc143L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc143R -> (EL*sw)/cw,
     gc144L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc144R -> (EL*sw)/cw,
     gc145L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc145R -> (EL*sw)/cw,
     gc146 -> -1/3*EL,
     gc147 -> (2*EL)/3,
     gc148 -> GS,
     gc149 -> GS,
     gc150 -> (EL*sw)/(3*cw),
     gc151 -> (-2*EL*sw)/(3*cw)};

